Meta/user invitation UI
openforis/fra-platform pull request #1086
Opened 2021-12-22 09:06 UTC by rfontanarosa

2021-12-22 12:13 UTC, sorja commented on client/basePaths.ts
> +    ) => _generate('assessment', countryIso, assessmentType),
note:
path fixed as discussed (otherwise it would match any url format `addr.com/a/b`)

2021-12-22 12:16 UTC, sorja commented on client/pages/Login/Login.tsx
> +      <Route exact path={BasePaths.Login.invitation()}>
Should we move as last route?
Should we wrap with `<Switch>`?

2021-12-22 14:43 UTC, sorja commented on client/pages/Login/Invitation/Invitation.tsx
> +  const invitedUser = useAppSelector((state) => state.login.invitedUser)
create hook in `store/login/hooks` and export it in `store/login/index`
`store/login/hooks/index.ts` : `export const useInvitedUser = () => useAppSelector((state) => state.login.invitedUser)`

2021-12-22 14:44 UTC, sorja commented on client/pages/Login/Invitation/Invitation.tsx
> +        <>
Fragment probably not needed

2021-12-22 14:45 UTC, sorja commented on client/pages/Login/Invitation/Invitation.tsx
> +      {loggedUser && invitedUser && loggedUser.email === invitedUser.email ? (
Better create a separate variable ex:
`const isSameUser = loggedUser?.email === invitedUser?.email`

2021-12-22 14:45 UTC, sorja commented on client/store/login/slice.ts
> +    // Add reducers for additional action types here, and handle loading state as needed
This comment can be removed

2021-12-22 14:46 UTC, sorja commented on client/store/login/slice.ts
> +    builder.addCase(acceptInvitation.fulfilled, (state, { payload }) => {
Should we handle error case?
```
builder
  .addCase(acceptInvitation.fulfilled, (state, { payload }) => { /* success case */ })
  .addCase(acceptInvitation.rejected, (state, { payload }) => { /* error case */ })

2021-12-22 14:46 UTC, sorja commented on client/store/login/slice.ts
> +    builder.addCase(acceptInvitation.fulfilled, (state, { payload }) => {
Even `acceptInvitation.pending` could be handled to display user something is going on (loading?)

2021-12-23 11:25 UTC, minotogna requested changes

2021-12-23 11:25 UTC, minotogna commented on server/controller/user/readByInvitation.ts
> +    const user = await UserRepository.read({ user: { id: userRole.userId } }, t)
the userRole is already part of the user.
this method should return only the User.

2021-12-23 11:25 UTC, minotogna approved these changes

2021-12-23 11:25 UTC, merged