original data point get/create and cycle schema management
openforis/fra-platform pull request #1147
Opened 2022-02-09 16:15 UTC by rfontanarosa

part of #1126

2022-02-09 16:53 UTC, minotogna requested changes

2022-02-09 16:53 UTC, minotogna commented on server/db/schemas.ts
> +  `assessment_${assessmentName}_${cycleName}`
the two methods are above. why duplicate them ?

2022-02-09 16:53 UTC, minotogna commented on server/repository/assessmentCycle/createCycleSchema.ts
> +    assessment: Pick<Assessment, 'props'>
why Pick? cant this just be Assessment ?

2022-02-09 16:53 UTC, minotogna commented on server/repository/assessmentCycle/createCycleSchema.ts
> +export const createCycleSchema = async (
call this method createSchema.

2022-02-09 16:53 UTC, minotogna commented on server/repository/assessmentCycle/index.ts
> +  removeCycleSchema,
call these methods:
create Schema, removeSchema

2022-02-09 16:53 UTC, minotogna commented on server/repository/originalDataPoint/create.ts
> +    originalDataPoint: Pick<OriginalDataPoint, 'countryIso' | 'year'>
why pick again ?

2022-02-09 16:53 UTC, minotogna commented on server/repository/originalDataPoint/read.ts
> +export const read = async (
call this method getOne

2022-02-12 06:55 UTC, minotogna commented on server/repository/assessmentCycle/index.ts
> +  createSchema,
dove è usato il metodo createSchema?

2022-02-12 15:30 UTC, rfontanarosa commented on server/repository/assessmentCycle/index.ts
> +  createSchema,
rimosso

2022-02-12 16:25 UTC, rfontanarosa commented on jest.config.js
> -  testMatch: ['**/integration/index.ts'],
we are now using a generic format based on extension instead of hardcode the name of the file

2022-02-12 16:30 UTC, sorja commented on jest.config.js
> -  testMatch: ['**/integration/index.ts'],
Sure, are we implementing some other tests which reside ex. next to the component we are testing? 
(
src/components/Button.tsx
src/components/Button.test.ts
)

2022-02-14 06:08 UTC, minotogna approved these changes

2022-02-14 06:09 UTC, merged