add required props for dataexport
openforis/fra-platform pull request #1270
Opened 2022-04-15 12:22 UTC by sorja

2022-04-15 13:08 UTC, minotogna requested changes

2022-04-15 13:08 UTC, minotogna commented on tools/dataMigration/migrateMetadata/getRow.ts
> +    row.props.variableExport = rowSpec.variableExport
Now we should only use variableName
All rows have it now

2022-04-15 13:21 UTC, minotogna commented on webapp/sectionSpec/rowSpec.ts
> +  labelKey?: string
Let's add now an object label with properties key, params, props
Btw where is it needed ?

2022-04-19 14:17 UTC, sorja commented on meta/assessment/row.ts
> +  variableExport?: string
comment/remove variableExport

2022-04-19 18:13 UTC, minotogna requested changes

2022-04-19 18:13 UTC, minotogna commented on meta/assessment/row.ts
> +  labelParams?: Record<string, string>
call this key, prefix, params

2022-04-20 06:40 UTC, minotogna approved these changes

2022-04-20 06:40 UTC, merged