websocket navigation status update
openforis/fra-platform pull request #1337
Opened 2022-05-20 12:42 UTC by rfontanarosa

close #1292

2022-05-20 14:43 UTC, minotogna requested changes

2022-05-20 14:43 UTC, minotogna commented on client/components/MessageCenter/Topic/Topic.tsx
> +        ReviewActions.getReviewSummary({ countryIso, assessmentName: assessment.props.name, cycleName: cycle.name })
Questo non funziona perché :

Utente A non ha nessun topic aperto , ma ha letto tutti i messaggi quindi il review summary saranno tutti blu .

Utente B apre un topic Ed Invia il messaggio .

Chi dovrebbe ricevere gli aggiornamenti sul review summary?
Entrambi 

Secondo la logica del codice , solo utente B

2022-05-23 12:06 UTC, rfontanarosa commented on client/components/MessageCenter/Topic/Topic.tsx
> +        ReviewActions.getReviewSummary({ countryIso, assessmentName: assessment.props.name, cycleName: cycle.name })
non avevo acceso il cervello. ora funziona.

2022-05-24 08:12 UTC, minotogna requested changes

2022-05-24 08:12 UTC, minotogna commented on client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
> +  }, [])
they go in the same useEffect with parameters countryIso, assessmentName, cycleName

2022-05-24 09:13 UTC, minotogna approved these changes

2022-05-24 09:14 UTC, merged