Initial commit for Dashboard
openforis/fra-platform pull request #1349
Opened 2022-05-27 14:37 UTC by sorja

# First 
## part of #1333 
![image](https://user-images.githubusercontent.com/5508251/170720941-936f3946-7ba0-4f68-b384-5673db9bae7d.png)

- [ ] CarbonGrowingStock
- [ ] ForestArea
- [ ] ForestAreaPercent
- [ ] ForestAreaWithinProtectedAreas
- [ ] ForestOwnership
- [ ] hooks (data fetching)
- [ ] NaturallyRegeneratingForest
- [ ] PrimaryDesignatedManagementObjective
- [ ] PrimaryForest
- [ ] utils (chart preferences and options)

2022-05-27 14:38 UTC, sorja commented on client/components/Chart/utils/ChartColors.ts
> +export enum ChartColors {
Todo: this file will be removed

2022-05-27 14:39 UTC, sorja commented on client/components/Chart/utils/getChartOptions.ts
> +import { Numbers } from '@core/utils/numbers'
This file will be removed

2022-05-27 14:44 UTC, sorja commented
market as draft until extra files removed and some code cleaned

2022-05-31 14:38 UTC, minotogna requested changes

2022-05-31 14:38 UTC, minotogna commented on client/pages/AssessmentHome/FraHome/FraHome.tsx
> +      {displayTabs ? (
it was already handled. now there's no need to add this. Dashboard is always added. leave it as it was

2022-05-31 14:38 UTC, minotogna commented on client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx
> +  // TODO Missing data
can u specify what data is missing ?

2022-05-31 14:38 UTC, minotogna commented on client/pages/Dashboard/components/table/table.tsx
> +const Table = (props: Props) => {
file name and folder name upper case

2022-05-31 14:38 UTC, minotogna commented on i18n/resources/en/statisticalFactsheets.js
> +    otherOrUnknown: 'Other or unknown',
should other languages be updated as well ?

2022-05-31 14:42 UTC, minotogna commented on client/pages/AssessmentHome/FraHome/FraHome.tsx
> +      {displayTabs ? (
check useSections

2022-05-31 15:21 UTC, sorja commented on client/pages/Dashboard/components/table/table.tsx
> +                    const nodeValue = tableData[countryIso][tableNames[0]][column]?.[variable]
In this case we have exact values for tableName, columnName and variableName; tableDatas helper wants Type Table, Col, Row so I would need to create objects, I think this is readable enough like this for this single case

2022-05-31 16:59 UTC, minotogna approved these changes

2022-05-31 16:59 UTC, merged