edit user roles
openforis/fra-platform pull request #1425
Opened 2022-07-29 10:34 UTC by rfontanarosa

closes #1388

2022-08-02 07:13 UTC, minotogna commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +const CountryRole = (props: Props) => {
const CountryRoles:React.FC<Props> = (props) => { 
....

2022-08-02 07:13 UTC, minotogna commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +import './CountryRoles.scss'
add styles to CountryRoles.scss

2022-08-02 07:13 UTC, minotogna commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +  const _onClose = (selection: Array<string>, role: RoleName) => {
useCallback

2022-08-02 07:13 UTC, minotogna commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +  const _toggleAdmin = () => {
useCallback

2022-08-02 07:13 UTC, minotogna commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +            <div key={role} className="edit-user__form-field-role-container validation-error-sensitive-field">
extract it to CountryRole

2022-08-02 13:35 UTC, rfontanarosa commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +            <div key={role} className="edit-user__form-field-role-container validation-error-sensitive-field">
what do you mean?

2022-08-02 15:26 UTC, minotogna commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +            <div key={role} className="edit-user__form-field-role-container validation-error-sensitive-field">
to create an inner Component

2022-08-02 15:27 UTC, minotogna requested changes

2022-08-02 15:27 UTC, minotogna commented on server/repository/public/user/update.ts
> +  await Promise.all(userRolePromises)
we need to ensure only admin can updates the roles. add this check in the controller.

Plus, we need to handle the 'deactivate' functionality.

2022-08-04 06:51 UTC, minotogna requested changes
c'è un problema di compilazione in server/controller/user/acceptInvitaion

2022-08-04 06:51 UTC, minotogna commented on client/components/EditUserForm/CountryRoles/CountryRoles.tsx
> +const CountryRole: React.FC<CountryRoleProps> = ({ onClick, role, user }) => {
preferibile spostarlo nel suo proprio file

2022-08-04 06:51 UTC, minotogna commented on server/repository/public/user/update.ts
> +  if (isAdministrator) {
per renderlo più error free, creiamo un metodo esterno updateRoles che viene invocato dal Controller se è administrator

2022-08-04 12:35 UTC, rfontanarosa commented on server/controller/user/update.ts
>      // TODO: Add activity log entry (public schema?)
at the moment the activity works only with the assessment schema, but the users and the roles are stored inside public schema

2022-08-04 13:10 UTC, minotogna approved these changes

2022-08-04 13:10 UTC, merged