message board unread messages
openforis/fra-platform pull request #1432
Opened 2022-08-03 06:45 UTC by rfontanarosa

closes #1407

2022-08-08 06:36 UTC, sorja commented on client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoard.tsx
> +                {data.unreadMessages > 0 && <div className="landing__user-message-count">{data.unreadMessages}</div>}
should we extract unreadMessages?

2022-08-09 14:09 UTC, minotogna requested changes

2022-08-09 14:09 UTC, minotogna commented on common/api/endpoint/ApiEndPoint.ts
> +      getUnreadChatMessages: () => apiPath('stats', 'getUnreadChatMessages'),
There should be only one endpoint and it's generic .

2022-08-09 14:09 UTC, minotogna commented on server/controller/messageCenter/index.ts
> +  getUnreadChatMessages: MessageTopicUserRepository.getUnreadChatMessages,
Only one generic method

2022-08-09 14:09 UTC, minotogna commented on server/repository/assessmentCycle/messageTopicUser/index.ts
>    getReviewSummary,
Only one generic method

2022-08-10 09:11 UTC, minotogna requested changes

2022-08-10 09:11 UTC, minotogna commented on server/api/messageCenter/getUnreadMessages.ts
> +      type: MessageTopicType
You need to pass the topic key and the response should return only one unread count ( only for the combination of assessment, cycle , countryIso , topicKey)

2022-08-11 09:45 UTC, minotogna approved these changes

2022-08-11 09:46 UTC, merged