recent activity tab
openforis/fra-platform pull request #1451
Opened 2022-08-22 08:54 UTC by rfontanarosa

closes #1434

2022-08-25 09:31 UTC, minotogna requested changes

2022-08-25 09:31 UTC, minotogna commented on server/api/assessment/getActivities.ts
> +export const getActivities = async (req: CycleDataRequest, res: Response) => {
this goes under server/api/cycleData

2022-08-25 09:31 UTC, minotogna commented on server/api/cycleData/table/persistNodeValues.ts
> +          section,
pass the parameter as sectionName. this should be ```sectionName:section```
in CycleDataController.persistNodeValue and all related method use sectionName

2022-08-25 09:31 UTC, minotogna commented on server/repository/assessment/activityLog/getCycleDataActivities.ts
> +          and a.message not in ('deleteComment', 'nodeValueCalculatedUpdate', 'updateCountry')
use affermative condition. message in (...)

2022-08-25 11:04 UTC, sorja commented on common/api/endpoint/ApiEndPoint.ts
> +    activities: () => apiPath('cycleData', 'activities'), // is it correct?
it is correct (remove comment)

2022-08-25 11:07 UTC, sorja commented on client/pages/AssessmentHome/FraHome/RecentActivity/RecentActivityItem/RecentActivityItem.scss
> +  padding: 48px;
should we use `$spacing-xl: 48px;`?

2022-08-25 11:10 UTC, sorja commented on server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts
> +  const { assessment, cycle, countryIso, section, tableName, variableName, colName, user } = props
sectionName?

2022-08-25 11:11 UTC, sorja commented on server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateNode.ts
> +      section,
sectionName?

2022-08-25 11:11 UTC, sorja commented on server/controller/cycleData/persistNodeValue/persistNode/persistNode.ts
> +    section,
sectionName?

2022-08-25 11:11 UTC, sorja commented on server/controller/cycleData/persistNodeValue/persistNode/persistNode.ts
> +    section,
section: sectionName for now maybe

2022-08-25 11:11 UTC, sorja commented on server/controller/cycleData/persistNodeValue/props.ts
> +  section?: string
sectionName

2022-08-25 11:12 UTC, sorja approved these changes

2022-08-26 08:26 UTC, minotogna approved these changes

2022-08-26 08:26 UTC, merged