bulkdownload fra years query update
openforis/fra-platform pull request #1524
Opened 2022-09-18 10:29 UTC by sorja

2022-09-19 07:54 UTC, rfontanarosa approved these changes

2022-09-19 10:30 UTC, minotogna requested changes

2022-09-19 10:30 UTC, minotogna commented on src/server/repository/assessmentCycle/data/getFraYearsDataQuery.ts
> +where cc.country_iso not ilike 'X%'
this query is very difficult to maintain and understand.
no comments, no dynamic generations. this cannot be committed like this. 
a more depth review is needed.

2022-09-19 10:36 UTC, rfontanarosa approved these changes

2022-09-21 13:44 UTC, minotogna approved these changes

2022-09-21 13:44 UTC, merged