Add support for Select all for regions in country modal desktop
openforis/fra-platform pull request #1526
Opened 2022-09-19 12:04 UTC by sorja

Resolves #1517 
- [x] Desktop
- [x] Mobile

Note:
Feature hides Select All/Unselect All when all countries of region are selected under another role

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/5508251/191227814-926ba0cf-f47e-4f91-a150-3cfab14db30a.png">

<img width="785" alt="image" src="https://user-images.githubusercontent.com/5508251/191228412-e7d09ab1-de30-47c8-b435-5d5c8d1b8b02.png">

2022-09-19 14:30 UTC, rfontanarosa approved these changes

2022-09-20 05:09 UTC, minotogna requested changes
Select / unselect all should be visible always and select / deselect enabled countries .

Plus , can the button be located on the right of the region label ?

2022-09-20 10:44 UTC, minotogna requested changes
move  select/all unselect all next to the label with 4/8 px distance

2022-09-20 11:40 UTC, sorja commented
> move select/all unselect all next to the label with 4/8 px distance

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/5508251/191248345-dc8478c0-e99e-4a62-b1bb-d7d4b2ab0efa.png">

2022-09-20 14:05 UTC, minotogna commented on src/client/styles/checkbox.scss
> +  min-width: 14px;
why should be this bigger than 14px?

2022-09-20 14:32 UTC, sorja commented on src/client/styles/checkbox.scss
> +  min-width: 14px;
There was weird issue where the checkbox would clip to 12px with `width` but would work with `min-width`; seems ot be fixed now so reverted back

2022-09-20 14:42 UTC, minotogna approved these changes

2022-09-20 14:44 UTC, merged