calculation fix
openforis/fra-platform pull request #1650
Opened 2022-10-25 12:26 UTC by rfontanarosa

close #1641

2022-10-25 15:09 UTC, minotogna requested changes

2022-10-25 15:09 UTC, minotogna commented on src/meta/assessment/assessmentMetaCache.ts
> +  colName?: string
can u remove this?

2022-10-25 15:13 UTC, minotogna commented
have you tested if it works by updated 2025 column ? in 2025 cycle ?

2022-10-25 21:01 UTC, rfontanarosa commented on src/meta/assessment/assessmentMetaCache.ts
> +  colName?: string
it is used to filter visitedVariables

2022-10-26 08:25 UTC, minotogna approved these changes

2022-10-26 14:06 UTC, sorja approved these changes

2022-10-26 14:07 UTC, merged