eslint 8.22.0
openforis/fra-platform pull request #1679
Opened 2022-11-06 16:01 UTC by sorja

2022-11-06 16:27 UTC, minotogna requested changes
Why not a full dependency upgrade ?

2022-11-06 16:44 UTC, sorja commented
> Why not a full dependency upgrade ?

can do, was doing playwright stuff and everything broke so opened a separate pr only for the needed change for now

full upgrade can take time if apis change / no backwards compatibility


it can be done, but will do the playwright init first

2022-11-06 18:57 UTC, minotogna commented
> > Why not a full dependency upgrade ?
> 
> can do, was doing playwright stuff and everything broke so opened a separate pr only for the needed change for now
> 
> full upgrade can take time if apis change / no backwards compatibility
> 
> it can be done, but will do the playwright init first

sounds good : 👍

2022-11-06 18:57 UTC, minotogna approved these changes

2022-11-07 08:32 UTC, rfontanarosa approved these changes

2022-11-07 08:33 UTC, merged