row.props: calculateFn and validateFn under cycle.uuid
openforis/fra-platform pull request #1687
Opened 2022-11-08 14:30 UTC by sorja

- [x] row.calculateFn
- [x] row.validateFns
- [ ] metacache

2022-11-08 15:09 UTC, minotogna requested changes
really good pr 👍 
just col calculateFn prop should by by cycle

2022-11-08 15:09 UTC, minotogna commented on src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts
> +          const node = await calculateNode({ ...evaluateProps, expression: row.props.calculateFn[cycle.uuid] }, client)
also col.props.calculateFn should be by cycle

2022-11-08 15:11 UTC, sorja commented on src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts
> +          const node = await calculateNode({ ...evaluateProps, expression: row.props.calculateFn[cycle.uuid] }, client)
good catch, wasn't 100% sure about it, will do

2022-11-09 08:56 UTC, minotogna requested changes

2022-11-09 08:56 UTC, minotogna commented on src/meta/assessment/row.ts
> +  validateFns?: Record<string, Array<string>>
remove comment and use CycleUuid

2022-11-09 08:56 UTC, minotogna commented on src/test/sectionSpec/colSpec.ts
> +import { CycleUuid } from '@meta/assessment/cycle'
CycleUuid must be imported from '@meta/assessment'

2022-11-09 08:56 UTC, minotogna commented on src/test/sectionSpec/rowSpec.ts
> +import { CycleUuid } from '@meta/assessment/cycle'
CycleUuid must be imported from '@meta/assessment'

2022-11-09 09:37 UTC, minotogna approved these changes

2022-11-09 12:01 UTC, rfontanarosa approved these changes

2022-11-09 12:02 UTC, merged