added specific getAreas permission
openforis/fra-platform pull request #1723
Opened 2022-11-17 16:57 UTC by rfontanarosa

2022-11-17 18:07 UTC, sorja commented
should we use express-validation like here
https://github.com/openforis/fra-platform/pull/1677

2022-11-18 08:26 UTC, minotogna requested changes

2022-11-18 08:26 UTC, minotogna commented on src/server/middleware/auth.ts
> +  else _next(!!user, next)
When Assessment and cycle are specified , it's needed to check that the user has read view permission to them.

The condition should be if not Assessment and not cycle then _next else requireView

2022-11-18 08:26 UTC, minotogna commented
> should we use express-validation like here
> 
> https://github.com/openforis/fra-platform/pull/1677

Not really

2022-11-21 13:27 UTC, sorja approved these changes

2022-11-22 13:40 UTC, rfontanarosa commented on src/server/middleware/auth.ts
> +  else _next(!!user, next)
but requireVIew needs CountryIso which is something not related to this.

what about adding

```
const canViewCycle = (props: { cycle: Cycle; user: User }): boolean => {
  const { cycle, user } = props
  if (cycle.published) return true
  if (Users.isAdministrator(user)) return true

  return false
}
```

and checking

```
const requireGetAreas = async (req: Request, _res: Response, next: NextFunction) => {
  const { assessmentName, cycleName } = <Record<string, string>>{ ...req.params, ...req.query, ...req.body }
  if (!assessmentName && !cycleName) next()
  const user = Requests.getRequestUser(req)
  const { cycle } = await AssessmentController.getOneWithCycle({ assessmentName, cycleName })
  _next(Authorizer.canViewCycle({ cycle, user }), next)
}
```

2022-11-22 16:41 UTC, minotogna commented on src/server/middleware/auth.ts
> +  else _next(!!user, next)
yes, but if cycle is not published, and user is logged then user must have an active role in that cycle to be authorized to view

2022-11-28 12:59 UTC, closed without merging