auth improvements and fixes
openforis/fra-platform pull request #1760
Opened 2022-11-25 17:21 UTC by rfontanarosa

close #1755

2022-11-27 06:34 UTC, minotogna approved these changes

2022-11-28 04:44 UTC, minotogna requested changes
Post videos about use cases fixed

2022-11-28 11:36 UTC, sorja commented on src/i18n/resources/en/login.js
> +  noMatchingProvider:
was this added in i18n issue

2022-11-28 12:14 UTC, sorja approved these changes

2022-11-28 12:22 UTC, rfontanarosa commented on src/i18n/resources/en/login.js
> +  noMatchingProvider:
yes, they were

2022-11-28 14:55 UTC, minotogna approved these changes

2022-11-28 14:55 UTC, merged