fix roles
openforis/fra-platform pull request #1796
Opened 2022-12-02 13:09 UTC by sorja

you dont have a role if you dont accept it

2022-12-02 13:28 UTC, minotogna approved these changes

2022-12-02 14:56 UTC, minotogna approved these changes

2022-12-02 17:23 UTC, sorja commented
pending changes

2022-12-03 19:52 UTC, minotogna commented on src/server/controller/user/invite.ts
> +    // TODO
What's here todo ?

2022-12-03 19:53 UTC, sorja commented on src/server/controller/user/invite.ts
> +    // TODO
@rfontanarosa

2022-12-05 08:47 UTC, minotogna requested changes

2022-12-05 08:47 UTC, minotogna commented on src/server/controller/user/invite.ts
> +    // TODO
remove this TODO

2022-12-05 13:23 UTC, rfontanarosa approved these changes

2022-12-05 14:04 UTC, minotogna commented on src/client/components/CountrySelect/CountryList/CountryList.tsx
> +              cycleUuid={cycle.uuid}
any reason for passing down cycleUuid ? can the inner components get cycle with useCycle ?

2022-12-05 14:23 UTC, minotogna approved these changes

2022-12-05 14:24 UTC, merged