Add tab bar with no links
openforis/fra-platform pull request #1882
Opened 2022-12-13 05:50 UTC by persas

Closes #1850. Navigation tab bar for registered users

2022-12-13 05:53 UTC, persas commented
Regarding this issue. I am not sure where the links of the tab bar should point to. In the FRA case, we have a bunch of pages that are under the `pages/AssessmentHome/FraHome` folder.  Do we have to move this to a different location and point to the same pages? Should it be different pages for panEu ?

2022-12-13 06:21 UTC, sorja commented
Can we have a screenshot or video?

2022-12-13 06:22 UTC, sorja commented
`import { useSections } from '../FraHome/hooks/useSections'`

Can be either moved one level higher to `AssessmentHome` or you can create similar one under `PanEuropeanHome` and add some Placeholder sections

2022-12-13 08:36 UTC, persas commented
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/23346350/207266338-c00c505b-ff61-4ca4-a2f0-2bb07c8bbd60.png">

2022-12-13 08:40 UTC, minotogna commented
> Regarding this issue. I am not sure where the links of the tab bar should point to. In the FRA case, we have a bunch of pages that are under the `pages/AssessmentHome/FraHome` folder.  Do we have to move this to a different location and point to the same pages? Should it be different pages for panEu ? 

They should point to similar path , like for Fra .
Can u import the components from fra home and then we'll see where to put them ?
So that we enable navigation in this pr .
Would that work ?

2022-12-13 09:51 UTC, persas commented
Links working with FRA components
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/23346350/207285091-00760bee-814a-43e0-8883-9b3a58d1eaea.png">

2022-12-13 10:20 UTC, persas commented
https://drive.google.com/file/d/1rocmYBIQ9am6mgi6624Dw_rXXTt42f3z/view?usp=share_link

2022-12-13 11:21 UTC, minotogna commented on src/client/pages/AssessmentHome/PanEuropeanHome/PanEuropeanHome.tsx
> +// eslint-disable-next-line import/no-unresolved
can we remove this disable ?

2022-12-13 11:24 UTC, minotogna requested changes

2022-12-13 11:24 UTC, minotogna commented on src/client/pages/AssessmentHome/PanEuropeanHome/hooks/useSections.tsx
> +  const sections: Array<Section> = [{ name: SectionNames.overview, component: Placeholder }]
the overview component must be created and includes:
<img width="1078" alt="Screenshot 2022-12-13 at 12 24 06" src="https://user-images.githubusercontent.com/1138156/207305276-84b67864-64c3-409d-8645-75f7f197672f.png">

2022-12-13 15:03 UTC, minotogna commented
Also, can you check the why style of the links doesn't match fra ?

2022-12-14 05:48 UTC, minotogna commented
> `import { useSections } from '../FraHome/hooks/useSections'`
> 
> 
> 
> Can be either moved one level higher to `AssessmentHome` or you can create similar one under `PanEuropeanHome` and add some Placeholder sections

I would leave things there . We'll refactor afterwards

2022-12-14 10:34 UTC, persas commented
https://user-images.githubusercontent.com/23346350/207572354-92b88446-b7e9-440c-a54a-fdfd2d12e9c6.mov

2022-12-14 14:33 UTC, minotogna approved these changes

2022-12-15 08:08 UTC, sorja approved these changes

2022-12-15 08:09 UTC, merged