ODP Edit: Add Primary forest -category, and display it in 1b table
openforis/fra-platform pull request #1914
Opened 2022-12-19 09:15 UTC by sorja

Resolves #1875

Add hardcoded primary_forest for ODPs which is calculated from percentages and requires naturally regenerating forest to be larger than 0 Primary forest for ODP is only available in cycle 2025

2022-12-19 14:21 UTC, minotogna requested changes

2022-12-19 14:21 UTC, minotogna commented on src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
> +      {hasNaturallyRegeneratingForest && <ForestCharacteristicsNaturallyRegenerating canEditData={canEditData} />}
this should go above plantation

2022-12-19 14:21 UTC, minotogna commented on src/i18n/resources/en.js
> +    ofWhichPrimaryForest: '…of which primary forest',
dont we have this translation already ? check fra.ts you can reuse that ?

2022-12-20 10:27 UTC, minotogna approved these changes

2022-12-20 10:54 UTC, rfontanarosa approved these changes

2022-12-20 10:55 UTC, merged