Update unit tests for estimation engine
openforis/fra-platform pull request #1946
Opened 2023-01-03 12:02 UTC by sorja

Resolves #1859

2023-01-03 12:03 UTC, minotogna approved these changes

2023-01-03 12:11 UTC, minotogna requested changes
Can u split dataset in each single file? Very difficult to review

2023-01-03 12:49 UTC, rfontanarosa approved these changes

2023-01-03 14:14 UTC, minotogna commented on src/server/service/estimates/dataset2.ts
> +  '1 - Repeat last - {1992, 2002}': [
Please each dataset its own file

2023-01-04 12:19 UTC, minotogna approved these changes

2023-01-04 12:19 UTC, merged