PR - New Toolbar
openforis/fra-platform pull request #1968
Opened 2023-01-05 18:12 UTC by rfontanarosa

close #1901 

https://user-images.githubusercontent.com/10047945/210850606-6ac8cf27-fc28-46fc-859e-e912e877ac8d.mov

https://user-images.githubusercontent.com/10047945/210850779-20f5e151-b6f7-4061-9992-87647f5f4c41.mov

2023-01-06 07:00 UTC, minotogna commented on src/client/components/PageLayout/Toolbar/Lock/Lock.tsx
> +  const canToggleLock = true // false // TODO
Is this todo still valid ?

2023-01-06 07:00 UTC, minotogna commented on src/client/components/PageLayout/Toolbar/Toolbar.tsx
> +const CountrySelect: React.FC = () => {
Rename to Toolbar

2023-01-06 07:00 UTC, minotogna commented on src/client/components/PageLayout/Toolbar/Toolbar.tsx
> +      {isFRA && isCountry && (
Remove isFra everywhere .

2023-01-06 07:00 UTC, minotogna commented on src/client/components/PageLayout/Toolbar/Toolbar.tsx
> +          {user && country && isFRA && isCountry && <Lock />}
Lock should be rendered if user can edit data

2023-01-06 07:00 UTC, minotogna commented on src/client/components/Tooltip/Tooltip.tsx
> +  children: JSX.Element
Do not use children props. Use react with children type

2023-01-07 16:59 UTC, rfontanarosa commented on src/client/components/PageLayout/Toolbar/Toolbar.tsx
> +          {user && country && isFRA && isCountry && <Lock />}
canEditData is for sections, canEditCountryProps doesn't consider Collaborators.

we need another level of permission based on Cycle/Country/Role. Let's discuss about it.

2023-01-09 07:59 UTC, sorja commented on src/client/components/PageLayout/Header/CycleSwitcher/CycleSwitcher.tsx
> +  const cycleChange = useCallback(
onCycleChange

2023-01-09 08:04 UTC, sorja approved these changes

2023-01-09 08:09 UTC, minotogna commented on src/client/components/PageLayout/Toolbar/Toolbar.tsx
> +          {user && country && isFRA && isCountry && <Lock />}
Lock is for edit data. Why another level of permissions ?

2023-01-09 08:13 UTC, minotogna requested changes

2023-01-09 08:13 UTC, minotogna commented on src/client/components/PageLayout/Toolbar/Toolbar.tsx
> +          {user && country && <Lock />}
Lock should be rendered if user can edit data

2023-01-09 17:52 UTC, minotogna approved these changes

2023-01-09 17:53 UTC, merged