PR - Table 5c Degraded forest- data validation rules
openforis/fra-platform pull request #2048
Opened 2023-01-19 14:46 UTC by rfontanarosa

close #2029

2023-01-23 11:11 UTC, minotogna requested changes

2023-01-23 11:11 UTC, minotogna commented on src/meta/assessment/node.ts
> +  raw: any
do not use any . string | Array<string> | null

2023-01-24 08:31 UTC, minotogna commented on src/meta/assessment/node.ts
> +  raw: any
NodeValue refactor: use generic for raw type

2023-01-24 08:32 UTC, minotogna approved these changes

2023-01-24 12:07 UTC, sorja approved these changes

2023-01-24 12:08 UTC, merged