Missing information toaster
openforis/fra-platform pull request #2147
Opened 2023-02-06 09:19 UTC by sorja

Resolves #2129 
https://user-images.githubusercontent.com/5508251/216933092-ed196871-7c7c-444e-a280-b5cfe781c0c6.mov

2023-02-06 10:00 UTC, rfontanarosa approved these changes, later dismissed

2023-02-06 10:05 UTC, minotogna requested changes
the risk is that user can also click somewhere else.
to fix this, we need the redirect to work in whatever page user clicks.

2023-02-06 10:06 UTC, sorja commented
> the risk is that user can also click somewhere else. to fix this, we need the redirect to work in whatever page user clicks.

I am unable to redirect anywhere else, what are the options?
Whatever page I open, I redirect here

2023-02-07 10:32 UTC, rfontanarosa approved these changes

2023-02-07 10:59 UTC, minotogna approved these changes

2023-02-07 10:59 UTC, merged