added classNames property co Col
openforis/fra-platform pull request #2554
Opened 2023-04-19 14:09 UTC by rfontanarosa

close #2414

2023-04-19 15:27 UTC, minotogna commented on src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
> +  const classes = Cols.getClasseNames({ col: colHeader, cycle })
call the method Cols.getClassNames, not Cols.getClasseNames

2023-04-19 16:07 UTC, sorja approved these changes, later dismissed

2023-04-20 09:45 UTC, minotogna requested changes
I don't see the migration step to update metadata. am I missing something ?

2023-04-20 12:39 UTC, minotogna approved these changes

2023-04-20 13:25 UTC, merged