2662 - Updated russian translation
openforis/fra-platform pull request #2670
Opened 2023-05-22 14:49 UTC by rfontanarosa

close #2662

2023-05-23 15:06 UTC, sorja approved these changes, later dismissed
👍

2023-05-23 15:23 UTC, minotogna requested changes

2023-05-23 15:23 UTC, minotogna commented on src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
> +                  {t(`${cycle.name === '2025' ? 'fra.extentOfForest.otherWoodedLand' : 'fraClass.otherWoodedLand'}`)}
Cycle should not explicitly referenced

2023-05-23 15:23 UTC, minotogna commented on src/test/migrations/steps/20230523104609-step-add-other-wooded-land-2005-label.ts
> +    rowGrowingStockAvg.id
The select query isn't necessary.

2023-05-23 20:38 UTC, rfontanarosa commented on src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
> +                  {t(`${cycle.name === '2025' ? 'fra.extentOfForest.otherWoodedLand' : 'fraClass.otherWoodedLand'}`)}
it is already used this way. i don't know how much is the effort to make it fully dynamic. it can be a new feature.

2023-05-24 10:13 UTC, minotogna approved these changes

2023-05-24 11:35 UTC, sorja approved these changes

2023-05-24 11:36 UTC, merged