2665 - Data validation tooltip
openforis/fra-platform pull request #2674
Opened 2023-05-23 20:41 UTC by rfontanarosa

close #2665

<img width="1073" alt="Screenshot 2023-05-23 alle 22 37 29" src="https://github.com/openforis/fra-platform/assets/10047945/b1a9bd89-9743-4927-98a2-8a5f4a578019">

2023-05-24 12:20 UTC, sorja commented
Looks good.. Maybe better if the tip starts from the cell and not from the data inside the cell?

2023-05-29 06:01 UTC, sorja commented on src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useClassName.ts
>    return className
Not sure but could we use classNames here?

2023-05-29 06:17 UTC, sorja commented on src/i18n/resources/en/assessmentSection.js
> +  dataTableHasErrors: 'Tables contains errors. Hover on the cell to see details.',
Update translations for other languages too

2023-05-29 06:20 UTC, sorja commented on src/meta/tooltip/tooltip.ts
> +  dataError = 'data-error-tooltip',
error-tooltip enough?

2023-05-29 16:03 UTC, rfontanarosa commented on src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useClassName.ts
>    return className
it is not because it is the same class overridden by several conditions

2023-05-30 04:20 UTC, minotogna reviewed
Update table error message and list style as discussed yesterday

2023-05-30 04:20 UTC, minotogna commented on src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
> +        !valid && dataValidationMessages.length > 0
Better to extract this from a hook

2023-05-30 04:20 UTC, minotogna commented on src/client/pages/PageRoutes/PageRoutes.tsx
> +      <div className="tooltips-container">
Better to extract this to the Tooltip component

2023-05-30 07:55 UTC, minotogna commented on src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
> +        !valid && dataValidationMessages.length > 0
a component data-tooltip-html={<ErrorMessages/>}

2023-05-30 10:09 UTC, minotogna submitted a review, later dismissed

2023-05-30 11:23 UTC, minotogna requested changes

2023-05-30 11:23 UTC, minotogna commented on src/client/pages/AssessmentSection/DataTable/Table/DataValidations/DataValidations.tsx
> -const translateErrorMessageParams = (t: TFunction, text: NodeValueValidationMessageParam): string => {
this must be included in tooltip

2023-05-30 11:33 UTC, rfontanarosa commented on src/client/pages/AssessmentSection/DataTable/Table/DataValidations/DataValidations.tsx
> -const translateErrorMessageParams = (t: TFunction, text: NodeValueValidationMessageParam): string => {
restored

2023-05-30 11:35 UTC, minotogna approved these changes

2023-05-30 12:11 UTC, sorja approved these changes

2023-05-30 12:12 UTC, merged