3016 admin countries page UI
openforis/fra-platform pull request #3035
Opened 2023-09-06 09:50 UTC by sorja

2023-09-06 11:38 UTC, minotogna requested changes

2023-09-06 11:38 UTC, minotogna commented on src/client/components/AreaSelector/CountryList/CountryListRow/CountryListRow.tsx
> -            <span className={`status-${status}-label`}>{i18n.t<string>(`assessment.status.${status}.label`)}</span>
any old css to remove ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/AreaSelector/CountryList/countryList.scss
> +    margin-left: $spacing-xs;
Is this needed? can u show a video o area selector ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/DataGrid/DataGrid.tsx
> +  style: undefined,
is this needed ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/CountryStatusIndicator/CountryStatusIndicator.tsx
> +    <span className="country-status-indicator">
maybe I would make it as div ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/TablePaginated.scss
> +    font-size: 14px;
don't we have font-NUMBER ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/TablePaginated.scss
> +    padding: 12px 10px;
better to use standard measures. spacing-NUMBER

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/TablePaginated.scss
> +    border-bottom-color: rgba(0, 0, 0, 0);
I wouldn't make them black, rather border-colour ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/TablePaginated.scss
> +    border-bottom-color: #dadada;
don't we have variables for colors  ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/TablePaginated.scss
> +    border-bottom: 1px solid #dadada;
don't we have variables for colors ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/TablePaginated.tsx
> +        <TablePaginatedBody columns={columns} path={path} />
since they are inner components, maybe better to remove prefix ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/TablePaginated.tsx
> +      <TablePaginatedCount path={path} />
also here, remove prefix ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/components/TablePaginatedBody.tsx
> +
by default, we create components in FolderUppercase, then index.ts and then Components.tsx

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/components/TablePaginatedBody.tsx
> +    // eslint-disable-next-line react/jsx-no-useless-fragment
why double fragment ? is outside fragment needed ?

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/components/TablePaginatedCount.tsx
> +
see components convention comment

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/components/TablePaginatedBody.tsx
> +            `${rowIndex}_${datum}`
use String(rowIndex) and get rid of eslint disable

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/components/TablePaginatedCount.tsx
> +
create inner css

2023-09-06 11:38 UTC, minotogna commented on src/client/components/TablePaginated/components/TablePaginatedHeader.tsx
> +
see components convention comment

2023-09-06 11:38 UTC, minotogna commented on src/client/pages/AdminCountries/AdminCountries.scss
> +    }
why this ?

2023-09-06 11:38 UTC, minotogna commented on src/client/pages/AdminCountries/AdminCountries.scss
> +    margin: initial;
also, why this ?

2023-09-06 11:38 UTC, minotogna commented on src/client/pages/AdminCountries/AdminCountries.tsx
>      ],
- last column: link to country is missing .
- see order of columns in the issue

2023-09-06 11:38 UTC, minotogna commented on src/client/store/ui/tablePaginated/actions/getData.ts
> +  const params = { assessmentName, cycleName, limit, page }
endpoint gets the offset.

2023-09-06 11:38 UTC, minotogna commented on src/i18n/resources/en/common.js
> +  invitationsSentCount: 'No. of Invitations sent',
wouldn't it better , as agreed, to put these two and usersCount to admin ?

2023-09-06 12:50 UTC, sorja commented on src/client/components/AreaSelector/CountryList/countryList.scss
> +    margin-left: $spacing-xs;
![image](https://github.com/openforis/fra-platform/assets/5508251/3c81108b-f94f-40bf-a375-37cc5035dd50)

without

2023-09-06 12:51 UTC, sorja commented on src/client/components/AreaSelector/CountryList/CountryListRow/CountryListRow.tsx
> -            <span className={`status-${status}-label`}>{i18n.t<string>(`assessment.status.${status}.label`)}</span>
it was used elsewhere, that's why i didnt remove
will open a note in project

2023-09-06 12:51 UTC, sorja commented on src/client/components/AreaSelector/CountryList/countryList.scss
> +    margin-left: $spacing-xs;
with
![image](https://github.com/openforis/fra-platform/assets/5508251/d0671f1a-352c-4f5a-90fe-371073289d02)

2023-09-06 12:54 UTC, sorja commented on src/client/components/DataGrid/DataGrid.tsx
> +  style: undefined,
optional props must be defined like this unfortunately

2023-09-06 13:15 UTC, sorja commented on src/client/components/TablePaginated/components/TablePaginatedBody.tsx
> +    // eslint-disable-next-line react/jsx-no-useless-fragment
in this case, yes

![image](https://github.com/openforis/fra-platform/assets/5508251/752ad213-f510-462f-9094-8964ec7fae49)

2023-09-06 17:47 UTC, minotogna commented on src/client/components/AreaSelector/CountryList/countryList.scss
> +    margin-left: $spacing-xs;
before it used country-selection-list__secondary-col. can u wrap the indicator within the country-selection-list__secondary-col ?

2023-09-06 17:49 UTC, minotogna commented on src/client/components/TablePaginated/Body/Body.tsx
> +        <React.Fragment key={`${String(rowIndex)}_${datum}`}>
I don't know if it's a good idea to pass the entire object as key. can this just be row_rowIndex ?

2023-09-06 17:49 UTC, minotogna commented on src/client/components/TablePaginated/Count/Count.scss
> +  margin-top: -1px;
why this?

2023-09-06 17:51 UTC, minotogna commented on src/client/components/TablePaginated/Count/Count.tsx
> +      {Object.entries(count).map(([key, value]) => (
I would probably just use total here and simplify this. In other components we'll how to pass a custom Counter. what do you think?

2023-09-06 17:54 UTC, minotogna commented on src/i18n/resources/en/common.js
> +  usersCount: 'No. of Users',
also this would go to admin ?

2023-09-07 07:56 UTC, minotogna approved these changes

2023-09-07 07:56 UTC, merged