added rough screenshot tool
openforis/fra-platform pull request #3478
Opened 2024-02-07 12:03 UTC by sorja

example output

![screenshot_FIN](https://github.com/openforis/fra-platform/assets/5508251/f99243bd-450f-4e61-9336-85f5539f47d3)

2024-02-07 13:44 UTC, minotogna commented on package.json
> +    "puppeteer-cluster": "^0.23.0",
Should  this go under dev dependencies ?
Doesn't it get imported from puppeteer ?

2024-02-07 13:44 UTC, minotogna commented on src/tools/screenshotWebpage.js
> +const puppeteer = require('puppeteer')
Better to use typescript ?

2024-02-07 13:44 UTC, minotogna commented on src/tools/screenshotWebpage.js
> +]
Better to fetch country isos ?

2024-02-08 07:32 UTC, sorja commented on src/tools/screenshotWebpage.js
> +const puppeteer = require('puppeteer')
sure, this was just a quick tool to quickly get the request done but i can change it to TS

2024-02-26 11:12 UTC, sorja commented
@minotogna let me know if this should be converted to TypeScript
from my side we can leave it as it is in JavaScript, as it is rarely used and is more a reference if we need to run this tool again

2024-02-26 13:07 UTC, minotogna approved these changes

2024-02-26 13:08 UTC, minotogna requested changes
Why not ts ?

2024-02-26 13:11 UTC, minotogna commented
> @minotogna let me know if this should be converted to TypeScript
> 
> from my side we can leave it as it is in JavaScript, as it is rarely used and is more a reference if we need to run this tool again

@sorja it's always preferred typescript

2024-02-26 13:13 UTC, sorja commented
> Why not ts ?

to avoid compiling, but i can change to ts!
will do at some point, i guess this is not extremely high priority :)

2024-03-26 08:17 UTC, minotogna approved these changes

2024-03-26 08:22 UTC, merged