3214 - Files and links per Cycle #3404: Update activity log and sort items correctly
openforis/fra-platform pull request #3582
Opened 2024-02-29 12:07 UTC by sorja

2024-02-29 12:08 UTC, sorja commented on src/test/migrations/steps/20240110160726-step-public-file-ddl.ts
> +              props || jsonb_build_object('translation', jsonb_build_object('en', f.name))
fix typo, migrated props accidentally in fra2020 to repository.props.props fixed to repository.props

2024-03-01 09:57 UTC, sorja commented on src/test/migrations/steps/20240110160726-step-public-file-ddl.ts
> +const migrateStaticLinks = async () => {
remove separate migration file and run it here to have correct order

2024-03-01 10:02 UTC, sorja commented on web-resources/img/icons.svg
not sure what the issue is here

2024-03-01 10:10 UTC, minotogna requested changes

2024-03-01 10:10 UTC, minotogna commented on src/test/migrations/steps/20240110160726-step-public-file-ddl.ts
> +            return { [lang]: i18n.t(`${i18nBase}.${key}`) }
Please , remove those labels from translation files if not used anymore

2024-03-01 10:10 UTC, minotogna commented on web-resources/img/icons.svg
You cut 3 icons , please restore them .

2024-03-01 10:10 UTC, minotogna commented on src/test/migrations/steps/20240229102956-step-update-activity-log-section-cycle-uuid-repository.ts
> +                                and assessment.props ->> 'name' = 'fra')
These you could simply get from controller . But as you wish

2024-03-01 10:17 UTC, sorja commented on web-resources/img/icons.svg
Weird, I copied the svg content from `development` branch

2024-03-01 10:37 UTC, sorja commented
@minotogna 

i copied the svg from development , should be ok ?

2024-03-01 10:40 UTC, minotogna commented on web-resources/img/icons.svg
No! @sorja we added icons !

2024-03-01 10:40 UTC, sorja commented on web-resources/img/icons.svg
This svg is copied from `development`

Let me know

2024-03-01 10:48 UTC, minotogna commented
> @minotogna
> 
> i copied the svg from development , should be ok ?

no @sorja . as I already mentioned in a previous comment, we have added icons .

2024-03-01 10:48 UTC, minotogna commented on web-resources/img/icons.svg
what is the problem ?

2024-03-01 10:49 UTC, sorja commented on web-resources/img/icons.svg
@minotogna I think the .svg file got messed up when you merged the branch here: [c23bc28](https://github.com/openforis/fra-platform/pull/3404/commits/c23bc28d704eba2f5b4f7c27aa66bcba0cb82991)

I returned the svg to it's original state (= copied from development)

2024-03-01 10:53 UTC, minotogna requested changes
Icons are missing

2024-03-01 11:01 UTC, minotogna commented on web-resources/img/icons.svg
> +</svg>
restore the new line please

2024-03-01 12:23 UTC, minotogna approved these changes

2024-03-01 12:23 UTC, merged