3645 - Dashboard: No data placeholder [RFC]
openforis/fra-platform pull request #3761
Opened 2024-04-23 12:06 UTC by sorja

![image](https://github.com/openforis/fra-platform/assets/5508251/0dd337b7-b764-4bb7-9855-bcddfa344c9c)

TODO: Fix styling clean code correct variables etc

2024-04-25 08:33 UTC, minotogna requested changes
Can the wording say : 'No data available'

2024-04-25 08:33 UTC, minotogna commented on src/client/components/Dashboard/BarChart/BarChart.tsx
> +  if (!hasData) {
Can this be done only once for all components ? Maybe wrapping a common component ?
Duplicated code must be avoided ,always .

2024-04-25 12:51 UTC, minotogna commented on src/client/components/Dashboard/BarChart/hooks/useBarChartData.ts
> +  const data = chart.columns.map((columnName) => {
Can this be return directly ?

2024-04-25 12:51 UTC, minotogna commented on src/client/components/Dashboard/BarChart/hooks/useBarChartData.ts
> +    data: _data,
And rollback the name without _ ?

2024-04-25 12:51 UTC, minotogna commented on src/client/components/Dashboard/Dashboard.scss
> +  margin-bottom: $spacing-m;
Can u remove this please ?

2024-04-25 12:51 UTC, minotogna commented on src/client/components/Dashboard/NoData/NoData.scss
> +  min-height: 240px;
Does this create a resize effect ? And is no data rendered only after data is fetched ?

2024-04-25 12:51 UTC, minotogna commented on src/client/components/Dashboard/PieChart/hooks/usePieChartData.ts
> +  return data
Same as above

2024-04-25 12:51 UTC, minotogna commented on src/client/components/Dashboard/hooks/useHasData.ts
> +  const _data = useData(table)
Same as above

2024-04-25 12:51 UTC, minotogna commented on src/i18n/resources/en/statisticalFactsheets.js
> +  noData: 'No data available',
We should translate this . Can u send an email with screenshot to our colleagues please ?

2024-04-25 12:54 UTC, sorja commented on src/i18n/resources/en/statisticalFactsheets.js
> +  noData: 'No data available',
Sure, I there will be no other translations related to Dashboard?

2024-04-25 12:59 UTC, sorja commented on src/client/components/Dashboard/NoData/NoData.scss
> +  min-height: 240px;
NoData is rendered after data is fetched

Not sure about the resize effect, what do you mean exactly?

2024-04-25 13:00 UTC, sorja commented on src/client/components/Dashboard/NoData/NoData.scss
> +  min-height: 240px;
https://github.com/openforis/fra-platform/assets/5508251/ae1d9e2f-86ab-4e38-a354-f44efc792b88

Another video, hope it answers some questions

2024-04-25 14:19 UTC, minotogna commented on src/client/components/Dashboard/NoData/NoData.scss
> +  min-height: 240px;
Look at growing stock item .
First there's an empty table ,
Then a text no data . 
All content shifts.

To avoid this evident unpleasant effect to: render chart or no data only where there's certainty of the element to render and to give a fixed height to the dashboard item .

Would that work ?

2024-04-25 14:20 UTC, minotogna commented on src/client/components/Dashboard/hooks/useHasData.ts
> +  const _data = useData(table)
Can't this be just data ?

2024-04-25 14:20 UTC, minotogna commented on src/i18n/resources/en/statisticalFactsheets.js
> +  noData: 'No data available',
I don't think so . What do you think ?

2024-04-26 07:28 UTC, sorja commented on src/i18n/resources/en/statisticalFactsheets.js
> +  noData: 'No data available',
Asked for translations 👍

2024-04-26 07:29 UTC, sorja commented on src/client/components/Dashboard/NoData/NoData.scss
> +  min-height: 240px;
This was good advice - I added the border and fixed height for dashboard items and now it is much more pleasant to eye when the layout is static

2024-04-26 07:40 UTC, sorja commented
@minotogna 
I need to duplicate some code here:
https://github.com/openforis/fra-platform/pull/3761/commits/2f6e75e67eb41698eab13f83181828bd6673cf05

What do you suggest ?

We want to call the component function to trigger data fetching hooks, but we don't want to show the component (instead we return null)

Hope this makes sense

2024-04-26 07:43 UTC, sorja commented on src/client/components/Dashboard/NoData/NoData.scss
> +  min-height: 240px;
Video updated in PR

2024-04-26 13:00 UTC, minotogna commented
> @minotogna 
> 
> I need to duplicate some code here:
> 
> https://github.com/openforis/fra-platform/pull/3761/commits/2f6e75e67eb41698eab13f83181828bd6673cf05
> 
> 
> 
> What do you suggest ?
> 
> 
> 
> We want to call the component function to trigger data fetching hooks, but we don't want to show the component (instead we return null)
> 
> 
> 
> Hope this makes sense

Can this be done in the new component Item you recently added @sorja ?
Would that work ?

2024-04-26 13:02 UTC, sorja commented
> > @minotogna
> > I need to duplicate some code here:
> > [2f6e75e](https://github.com/openforis/fra-platform/commit/2f6e75e67eb41698eab13f83181828bd6673cf05)
> > What do you suggest ?
> > We want to call the component function to trigger data fetching hooks, but we don't want to show the component (instead we return null)
> > Hope this makes sense
> 
> Can this be done in the new component Item you recently added @sorja ? Would that work ?

I was thinking of creating top level hooks to dispatch all table data fetches in the top level (Items)

2024-04-26 17:46 UTC, minotogna commented
> > > @minotogna
> 
> > > I need to duplicate some code here:
> 
> > > [2f6e75e](https://github.com/openforis/fra-platform/commit/2f6e75e67eb41698eab13f83181828bd6673cf05)
> 
> > > What do you suggest ?
> 
> > > We want to call the component function to trigger data fetching hooks, but we don't want to show the component (instead we return null)
> 
> > > Hope this makes sense
> 
> > 
> 
> > Can this be done in the new component Item you recently added @sorja ? Would that work ?
> 
> 
> 
> I was thinking of creating top level hooks to dispatch all table data fetches in the top level (Items)

This sounds good @sorja .

2024-04-29 08:23 UTC, sorja commented
Update or create a hook to fetch all needed data (useData)
This is called from `Dashboard.tsx`

2024-04-30 09:21 UTC, minotogna commented on src/client/components/Dashboard/Item/Item.scss
> +.dashboard__item {
does this conflict with new style pr ?

2024-04-30 09:21 UTC, minotogna commented on src/client/components/Dashboard/Dashboard.tsx
> +import Item from 'client/components/Dashboard/Item/Item'
import from 'client/components/Dashboard/Item'

2024-04-30 09:21 UTC, minotogna commented on src/client/components/Dashboard/Item/Item.tsx
> +      {!hasData || isFetching ? <NoData /> : <div />}
why this empty div ?

2024-04-30 09:21 UTC, minotogna commented on src/client/components/Dashboard/Item/Item.tsx
> +      {!hasData || isFetching ? <NoData /> : <div />}
also, I see in NoData you return null if is fetching . however here you render this if isFetching.
It seems inconsistent to me.

2024-04-30 11:37 UTC, sorja commented on src/client/components/Dashboard/Item/Item.tsx
> +      {!hasData || isFetching ? <NoData /> : <div />}
Good point, result of refactoring some ifs...

Updated

2024-04-30 11:38 UTC, sorja commented on src/client/components/Dashboard/Item/Item.scss
> +.dashboard__item {
No, this introduced new element

![kuva](https://github.com/openforis/fra-platform/assets/5508251/adeb0c45-9712-493d-bb54-c1c941387f99)

2024-04-30 11:49 UTC, minotogna commented on src/client/components/Dashboard/Item/Item.scss
> +.dashboard__item {
would. you mind resetting this and we'll check together any further style improvements ?

2024-04-30 11:50 UTC, sorja commented on src/client/components/Dashboard/Item/Item.scss
> +.dashboard__item {
sure , resetting what ?

2024-04-30 11:52 UTC, minotogna commented on src/client/components/Dashboard/NoData/NoData.tsx
> +  if (isFetching) return null
isn't this redundant ?

<img width="242" alt="Screenshot 2024-04-30 at 13 51 25" src="https://github.com/openforis/fra-platform/assets/1138156/1285aebe-d5de-4f94-8f97-d677a27afde2">

2024-04-30 12:14 UTC, minotogna commented on src/client/components/Dashboard/Item/Item.scss
> +.dashboard__item {
the style of this item !

2024-04-30 12:22 UTC, sorja commented on src/client/components/Dashboard/Item/Item.scss
> +.dashboard__item {
sure 🔢

2024-04-30 12:25 UTC, minotogna approved these changes

2024-04-30 12:26 UTC, merged