3855 move files to s3 bucket
openforis/fra-platform pull request #3978
Opened 2024-09-27 10:55 UTC by sorja

- [ ] check migration step is `exists` query

implementation:
- create a bucket to s3
- implement new service `FileStorage` to write and read files
- remove column `file` from `public.file`

todo:
- [ ] src/server/repository/public/ddl/getCreatePublicSchemaDDL.ts update `public.file` with public migration
- investigate if we want to remove `public.file`

todo/check:
- [x] upload and view avatar
- [x] upload and view file from Links and repository
- [x] upload and view file from EditorWYSIWYG

2025-01-10 14:08 UTC, sorja commented
- [  ] Write a script to test all files

2025-01-16 10:14 UTC, minotogna commented on src/server/api/file/get.ts
> +import { FileRepository, fileTypes } from 'server/service/file_deprecated'
how come we have some deprecated code?

2025-01-16 10:14 UTC, minotogna commented on src/server/controller/cycleData/repository/getManyFiles.ts
> +  // eslint-disable-next-line no-restricted-syntax
what about Promises.each ?

2025-01-16 10:14 UTC, minotogna commented on src/tools/uploadToS3/index.ts
> +const uploadFileToS3 = async (filePath: string): Promise<void> => {
do we need this script ? if yes, should we move it under tools/s3Files ?

2025-01-16 10:23 UTC, sorja commented on src/server/api/file/get.ts
> +import { FileRepository, fileTypes } from 'server/service/file_deprecated'
https://github.com/openforis/fra-platform/issues/4214

It's pending this - it's just serving static files

What do you suggest? Keep filename as `file`?

![image](https://github.com/user-attachments/assets/5fc5baeb-c6d6-4bde-8b0a-a35de646c5ee)

2025-01-16 10:28 UTC, minotogna commented on src/server/api/file/get.ts
> +import { FileRepository, fileTypes } from 'server/service/file_deprecated'
Aaaa ok . Let's leave as it is then . We'll refactor later . No worries now

2025-01-16 17:04 UTC, minotogna requested changes
Removing a repository item doesn't remove the file from the s3 bucket. it should.

2025-01-20 14:35 UTC, minotogna approved these changes

2025-01-20 14:36 UTC, merged