4032 - Meta and integration test
openforis/fra-platform pull request #4054
Opened 2024-10-23 11:47 UTC by sorja

2024-10-23 11:58 UTC, minotogna requested changes
the comment in the previous PR should be updated.

2024-10-23 12:00 UTC, minotogna commented on src/meta/user/userRoles.ts
> +    return roleB.createdAt.localeCompare(roleA.createdAt)
should we use Dates instead ?

2024-10-23 12:00 UTC, minotogna commented on src/meta/user/userInvitations.ts
> +  isInvitationExpired,
I would not duplicate the name invitation in the methods. this utility works on invitations objects only

2024-10-23 12:02 UTC, minotogna commented on src/meta/user/userInvitation.ts
> +  cycleUuid: string
how come cycle is required and assessment not ?

2024-10-23 12:02 UTC, minotogna commented on src/meta/user/userRole.ts
> +  cycleUuid: string
same here... and are we still using assessment id ? or uuid ?

2024-10-23 12:06 UTC, sorja commented on src/meta/user/userRole.ts
> +  cycleUuid: string
Typo, also cycle should be optional (admin)

2024-10-23 12:07 UTC, sorja commented on src/meta/user/userInvitation.ts
> +  cycleUuid: string
I will mark in the main PR that we should check if assessmentUuid is really needed as an invitation can be related only to a single cycle, same as roles

What do you think?

#discussion

2024-10-23 12:08 UTC, minotogna commented on src/meta/user/userInvitation.ts
> +  cycleUuid: string
leave both, assessments and cycles for now. we'll talk in the near future about this. ok?

2024-10-23 12:09 UTC, sorja commented on src/meta/user/userInvitation.ts
> +  cycleUuid: string
sure - added in main pr so we don't forget

also something to keep in mind in the discussion:

if role/invitation has either, it should maybe mean it's for all cycles (avoid role duplication?)

2024-10-23 12:13 UTC, minotogna commented on src/meta/user/userInvitation.ts
> +  cycleUuid: string
an invitation is per cycle. same thing for the role. or did I misunderstood your comment ?

2024-10-23 12:14 UTC, minotogna commented
please check deepscan , the tests have some issues

2024-10-23 12:16 UTC, minotogna commented on src/meta/user/userInvitation.ts
> +  invitedByUserUuid?: string
is it possible to have an invitation without the inviter ?

2024-10-24 10:11 UTC, minotogna approved these changes
👍

2024-10-24 10:11 UTC, merged